### ISSUE TITLE
Problems with Notion the blog doesn't work

### ISSUE THREAD

**Issue by AntonioDEM** [ijjk/notion-blog#76] opened 2021-09-20 05:10 UTC
Mac book, OSX: 10.15.7 
Notion 2.0.17

I state that I am not an expert. i managed to get online with vercel and with the localhost.
in the .env file I manually entered the token and the blog id.
I used the code:

export NOTION_TOKEN = '<your-token>' and export BLOG_INDEX_ID = '<your-blog-index-id>'

but it's like it's not connected to Notion. It does not read the table I made following the instructions.

it's like it doesn't read the BLOG_INDEX_ID and the Notion_Token
I tried to insert it in many ways and nothing, it does not create any pages

Can you take a step by step video please?

[quello che vedo](https://ibb.co/0Fn5wqW) #

**Comment by ijjk** [comment] 2021-09-20 14:34
Hi, are you seeing any errors in your logs? If it fails to fetch the data it should say so in your deployment's function logs.

**Comment by YBerkayAltin** [comment] 2022-02-06 12:30
Did you find any solution?

**Comment by sota0121** [comment] 2022-02-27 17:20
Hi, I have the same problem. 
I saw function logs.

I created the table manually, So I think it said "run the create-table script".

```bash
[GET] /_next/data/FSYgZnDdqX101WjvgFtWj/blog.json
02:18:07:92
info  - Loaded env from /var/task/.env
2022-02-27T17:18:09.170Z	d65a9e52-2e6d-4e1b-8cb6-dc5b17a95f08	WARN	Failed to load Notion posts, have you run the create-table script?
```

![image](https://user-images.githubusercontent.com/30281161/155892569-46d90961-7cd3-4a5a-bad5-a7a19aef1f0b.png)

**Comment by sota0121** [comment] 2022-02-27 17:34
I ran the create-table.js scripts in local, but I got "failed to load Notion posts".


## Logs

```bash
$ docker compose up 
[+] Running 1/1
 ⠿ Container notion-blog-node-1  Recreated                                                                                 10.5s
Attaching to notion-blog-node-1
notion-blog-node-1  | yarn run v1.22.5
notion-blog-node-1  | $ next dev
notion-blog-node-1  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
notion-blog-node-1  | info  - Loaded env from /usr/src/app/.env
notion-blog-node-1  | info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
notion-blog-node-1  | Browserslist: caniuse-lite is outdated. Please run:
notion-blog-node-1  | npx browserslist@latest --update-db
notion-blog-node-1  | 
notion-blog-node-1  | Why you should do it regularly:
notion-blog-node-1  | https://github.com/browserslist/browserslist#browsers-data-updating
notion-blog-node-1  | event - compiled successfully
notion-blog-node-1  | event - build page: /
notion-blog-node-1  | wait  - compiling...
notion-blog-node-1  | event - build page: /next/dist/pages/_error
notion-blog-node-1  | event - compiled successfully
notion-blog-node-1  | event - build page: /blog
notion-blog-node-1  | wait  - compiling...
notion-blog-node-1  | event - compiled successfully
notion-blog-node-1  | Failed to load Notion posts, have you run the create-table script?
notion-blog-node-1  | wait  - compiling...
notion-blog-node-1  | event - compiled successfully
```

## Dockerfile , Compose file

```docker
FROM node:14.15.3
WORKDIR /usr/src/app

RUN curl https://deb.nodesource.com/setup_12.x | bash
RUN curl https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && apt-get install -y yarn
RUN apt install direnv

RUN yarn install
```

```yml
version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: sh -c "yarn dev"
    ports:
      - "3000:3000"
```

**Comment by sota0121** [comment] 2022-06-21 14:27
Hi guys !
This problem has been resolved by upgrading to latest revision.

Maybe, this problem caused by notion api spec upgrade about `src/lib/notion/queryCollection.ts`

src is [here](https://github.com/ijjk/notion-blog/blob/main/src/lib/notion/queryCollection.ts)

**Comment by ijjk** [comment] 2022-06-21 15:06
> This problem has been resolved by upgrading to latest revision

Closing per-above, thanks!

**Closed by ijjk** 2022-06-21 15:06 UTC
