### ISSUE TITLE
Invalid blog-index-id should be 32 characters long

### ISSUE THREAD

**Issue by mrrfly** [ijjk/notion-blog#32] opened 2020-06-05 07:12 UTC
Hello,

I got a bug or my problem in here.

I have followed the guidelines in  [here](https://github.com/ijjk/notion-blog#getting-blog-index-and-token)

My error is
`
Error: Invalid blog-index-id: "a3a2eb5f-e142-4a20-a164-c6f3ee2ddf43" should be 32 characters long. Info here https://github.com/ijjk/notion-blog#getting-blog-index-and-token
    at normalizeId (D:\13. NextJS\notion-blog\src\lib\notion\server-constants.js:8:11)
    at Object.<anonymous> (D:\13. NextJS\notion-blog\src\lib\notion\server-constants.js:19:23)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\13. NextJS\notion-blog\next.config.js:6:5)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

I tried this too
`
set NOTION_TOKEN="<REDACTED>" && set BLOG_INDEX_ID="a3a2eb5fe1424a20a164c6f3ee2ddf43"
`

and still getting error
`
Error: Invalid blog-index-id: "a3a2eb5fe1424a20a164c6f3ee2ddf43" should be 32 characters long. Info here https://github.com/ijjk/notion-blog#getting-blog-index-and-token
    at normalizeId (D:\13. NextJS\notion-blog\src\lib\notion\server-constants.js:8:11)
    at Object.<anonymous> (D:\13. NextJS\notion-blog\src\lib\notion\server-constants.js:19:23)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\13. NextJS\notion-blog\next.config.js:6:5)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

Maybe anyone can help me? Thx :D

**Comment by mrrfly** [comment] 2020-06-16 04:53
> That string is 31 characters long, your string should be 32 characters in the notion url

but i got blog-index-id from Notion

**Comment by jdetle** [comment] 2020-06-18 02:07
double check if you didn't miss a character, notion wont give you a 31 char string I promise

**Comment by mrrfly** [comment] 2020-06-18 02:50
> double check if you didn't miss a character, notion wont give you a 31 char string I promise

Maybe this picture can describe it
![notion1](https://user-images.githubusercontent.com/34133496/84972471-22098680-b149-11ea-803f-42b984f8af05.png)
![notion2](https://user-images.githubusercontent.com/34133496/84972474-233ab380-b149-11ea-9f7b-05e712f59119.png)

**Comment by ijjk** [comment] 2020-06-29 20:51
Hi, looking at the provided details I'm not able to reproduce any problems with this so I'm going to close the issue. If you are still having trouble with this feel free to reply with additional info and I'd be happy to take another look

**Closed by ijjk** 2020-06-29 20:51 UTC

**Comment by mrrfly** [comment] 2020-06-30 03:34
Okay Thx For Response :D
